/**
 * Tests for html/diff.js.
 *
 * The bulk of this runs the shared vectors in diff_vectors.json, which lambdas/api-v1/src/diff.rs
 * is checked against by `cargo test`. Because the two implementations are ports of one another,
 * these assert that JS generates byte-identical output, not merely a diff that happens to apply.
 */

import { describe, test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import { applyNoteDiff, applyStringDiff, diffStrings, formatNoteDiff } from "../html/diff.js";

const doc = JSON.parse(readFileSync(new URL("./diff_vectors.json", import.meta.url), "utf8"));
const vectors = doc.vectors;

/** The note diff for a vector, in the undo direction: diff(new, old). */
function generateNoteDiff(vector) {
    return formatNoteDiff(
        diffStrings(vector.new_title, vector.old_title),
        diffStrings(vector.new_body, vector.old_body),
    );
}

test("the vector file has vectors in it", () => {
    assert.ok(vectors.length > 0, "diff_vectors.json contained no vectors");
});

describe("generation matches the shared vectors byte for byte", () => {
    for (const vector of vectors) {
        test(vector.name, () => {
            assert.equal(generateNoteDiff(vector), vector.note_diff);
        });
    }
});

describe("applying the recorded diff undoes the edit", () => {
    for (const vector of vectors) {
        test(vector.name, () => {
            if (vector.note_diff === null) {
                assert.equal(vector.old_title, vector.new_title);
                assert.equal(vector.old_body, vector.new_body);
                return;
            }
            const applied = applyNoteDiff(
                {title: vector.new_title, body: vector.new_body}, vector.note_diff, false);
            assert.deepEqual(applied, {title: vector.old_title, body: vector.old_body});
        });
    }
});

describe("applying the recorded diff reversed redoes the edit", () => {
    for (const vector of vectors) {
        test(vector.name, () => {
            if (vector.note_diff === null) {
                return;
            }
            const applied = applyNoteDiff(
                {title: vector.old_title, body: vector.old_body}, vector.note_diff, true);
            assert.deepEqual(applied, {title: vector.new_title, body: vector.new_body});
        });
    }
});

describe("a diff generated by JS round trips through JS", () => {
    for (const vector of vectors) {
        test(vector.name, () => {
            const noteDiff = generateNoteDiff(vector);
            if (noteDiff === null) {
                return;
            }
            const undone = applyNoteDiff(
                {title: vector.new_title, body: vector.new_body}, noteDiff, false);
            assert.deepEqual(undone, {title: vector.old_title, body: vector.old_body});
            const redone = applyNoteDiff(undone, noteDiff, true);
            assert.deepEqual(redone, {title: vector.new_title, body: vector.new_body});
        });
    }
});

describe("applyNoteDiff", () => {
    test("does not modify the note it is given", () => {
        const note = {title: "the cat sat", body: "unchanged"};
        applyNoteDiff(note, "t:4[cat|dog]4", false);
        assert.deepEqual(note, {title: "the cat sat", body: "unchanged"});
    });

    test("leaves the body alone for a title-only diff", () => {
        const applied = applyNoteDiff({title: "abc", body: "xyz"}, "t:3[| def]", false);
        assert.deepEqual(applied, {title: "abc def", body: "xyz"});
    });

    test("leaves the title alone for a body-only diff", () => {
        const applied = applyNoteDiff({title: "abc", body: "xyz"}, "b:3[| def]", false);
        assert.deepEqual(applied, {title: "abc", body: "xyz def"});
    });

    test("stops at an unknown section key", () => {
        const applied = applyNoteDiff({title: "abc", body: "xyz"}, "q:3[| def]", false);
        assert.deepEqual(applied, {title: "abc", body: "xyz"});
    });
});

describe("diffStrings", () => {
    test("returns null for identical strings", () => {
        assert.equal(diffStrings("hello", "hello"), null);
    });

    test("returns null for two empty strings", () => {
        assert.equal(diffStrings("", ""), null);
    });
});

describe("formatNoteDiff", () => {
    test("returns null when neither field changed", () => {
        assert.equal(formatNoteDiff(null, null), null);
    });

    test("uses the t: form when only the title changed", () => {
        assert.equal(formatNoteDiff("3[a|b]", null), "t:3[a|b]");
    });

    test("uses the b: form when only the body changed", () => {
        assert.equal(formatNoteDiff(null, "3[a|b]"), "b:3[a|b]");
    });

    test("joins both forms with a pipe when both changed", () => {
        assert.equal(formatNoteDiff("1[a|b]", "2[c|d]"), "t:1[a|b]|b:2[c|d]");
    });
});

describe("applyStringDiff", () => {
    test("applies an unedited range and a change", () => {
        const result = applyStringDiff("hello world", "6[world|earth]", false);
        assert.equal(result.asApplied, "hello earth");
        assert.equal(result.remaining, "");
        assert.equal(result.appliesCleanly, true);
    });

    test("reverses a change when asked to", () => {
        const result = applyStringDiff("hello earth", "6[world|earth]", true);
        assert.equal(result.asApplied, "hello world");
        assert.equal(result.appliesCleanly, true);
    });

    test("unescapes the escaped characters", () => {
        const result = applyStringDiff("a]b", "1[\\]|\\|]1", false);
        assert.equal(result.asApplied, "a|b");
        assert.equal(result.appliesCleanly, true);
    });

    test("stops at a bare pipe and reports the rest as remaining", () => {
        const result = applyStringDiff("abc", "3|b:9[x|y]", false);
        assert.equal(result.asApplied, "abc");
        assert.equal(result.remaining, "|b:9[x|y]");
        assert.equal(result.appliesCleanly, true);
    });

    test("reports appliesCleanly false when the text to remove is not there", () => {
        const result = applyStringDiff("hello there", "6[world|earth]", false);
        assert.equal(result.appliesCleanly, false);
    });

    test("reports appliesCleanly false when the source runs out early", () => {
        const result = applyStringDiff("abc", "10", false);
        assert.equal(result.appliesCleanly, false);
    });

    test("reports appliesCleanly false when source characters are left over", () => {
        const result = applyStringDiff("abcdef", "3", false);
        assert.equal(result.asApplied, "abcdef");
        assert.equal(result.appliesCleanly, false);
    });

    test("counts an astral character as one character", () => {
        const result = applyStringDiff("I like \u{1F431} pets", "7[\u{1F431}|\u{1F436}]5", false);
        assert.equal(result.asApplied, "I like \u{1F436} pets");
        assert.equal(result.appliesCleanly, true);
    });

    test("throws on an unexpected character in the diff", () => {
        assert.throws(() => applyStringDiff("abc", "3x", false), /unexpected character/);
    });

    test("throws on an unexpected escape sequence", () => {
        assert.throws(() => applyStringDiff("abc", "[\\n|x]", false), /unexpected escape sequence/);
    });
});
